stages:
  - build
  - test

maven-build:
  stage: build
  tags:
    - brayden_tag
  script:
    - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk
    - export MAVEN_OPTS="-Dmaven.compiler.source=17 -Dmaven.compiler.target=17"
    - java -version
    - cd Backend
    - mvn package
  only:
    refs:
      - Brayden_CICD
    changes:
      - Backend/**/*

maven-test:
  stage: test
  tags:
    - brayden_tag
  script:
    - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk
    - export PATH=$JAVA_HOME/bin:$PATH
    - java -version
    - cd Backend
    - mvn test
  only:
    refs:
      - Brayden_CICD
    changes:
      - Backend/**/*