stages:
  - androidbuild
  - androidtest

android-build:
  image: afirefly/android-ci:java17
  stage: androidbuild
  tags:
    - ashten_tag
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/gradlew
  script:
    - cd Frontend
    - ./gradlew build               # gradle build
  only:
    refs:
      - Ashten_CICD
    changes:
      - Frontend/**/*

android-test:
  image: afirefly/android-ci:java17
  stage: androidtest
  tags:
    - ashten_tag
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/gradlew
  script:
    - cd Frontend
    - ./gradlew test               # gradle test
  only:
    refs:
      - Ashten_CICD
    changes:
      - Frontend/**/*
