stages:
  - build
  - test

maven-build:
  stage: build
  tags:
    - brayden_tag
  script:
    - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk
    - export MAVEN_VERSION=3.8.6
    - wget https://archive.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz
    - tar -xzf apache-maven-$MAVEN_VERSION-bin.tar.gz
    - export PATH=$PWD/apache-maven-$MAVEN_VERSION/bin:$PATH
    - java -version
    - mvn -version
    - cd Backend
    - mvn package
  only:
    refs:
      - Brayden_CICD
    changes:
      - Backend/**/*

maven-test:
  stage: test
  tags:
    - brayden_tag
  script:
    - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk
    - export MAVEN_VERSION=3.8.6
    - wget https://archive.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz
    - tar -xzf apache-maven-$MAVEN_VERSION-bin.tar.gz
    - export PATH=$PWD/apache-maven-$MAVEN_VERSION/bin:$PATH
    - java -version
    - mvn -version
    - cd Backend
    - mvn test
  only:
    refs:
      - Brayden_CICD
    changes:
      - Backend/**/*