maven-build:
  stage: mavenbuild
  tags:
    - brayden_tag
  script:
    - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk
    - export PATH=$JAVA_HOME/bin:$PATH
    - java -version  # for confirmation
    - cd Backend
    - mvn package
  only:
    refs:
      - Brayden_CICD
    changes:
      - Backend/**/*

maven-test:
  stage: maventest
  tags:
    - brayden_tag
  script:
    - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk
    - export PATH=$JAVA_HOME/bin:$PATH
    - java -version
    - cd Backend
    - mvn test
  only:
    refs:
      - Brayden_CICD
    changes:
      - Backend/**/*