              # more specifically - only when changes are made inside the 'Frontend' folder
stages:             # these stages (jobs) forms the CICD pipeline
  - mavenbuild      # this is a JOB to build your Springboot application
  - maventest       # this is a JOB to run tests in your Springboot application (it's okay you don't have any test for now)

maven-build:            
  stage: mavenbuild     # one of the stages listed above
  tags:                 # to specify which runner to execute this job
    - niall_CICD    # change to your runner's tag
  script:               # what to execute for this job
    - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk
    - export MAVEN_VERSION=3.8.6
    - wget https://archive.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz
    - tar -xzf apache-maven-$MAVEN_VERSION-bin.tar.gz
    - export PATH=$PWD/apache-maven-$MAVEN_VERSION/bin:$PATH
    - java -version
    - mvn -version
    - cd Backend
    - mvn package
  artifacts:            # where to output the packaged jar file, change 'Backend' to to where you have the pom.xml
    paths:
    - Backend/target/*.jar # change 'Backend' to where you have 'target' (do not add a / in the beginning)
  only:
    refs:
      - NiallCICD            # only to trigger the pipeline when changes are pushed to 'main'
    changes:
      - Backend/**/*    # more specifically - only when changes are made inside the 'Backend' folder

maven-test:             
  stage: maventest     # one of the stages listed above
  tags:
     - niall_CICD   # change to your runner's tag
  script:
    - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk
    - export MAVEN_VERSION=3.8.6
    - wget https://archive.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz
    - tar -xzf apache-maven-$MAVEN_VERSION-bin.tar.gz
    - export PATH=$PWD/apache-maven-$MAVEN_VERSION/bin:$PATH
    - java -version
    - mvn -version
    - cd Backend
    - mvn test
  only:
    refs:
      - NialLCICD            # only to trigger the pipeline when changes are pushed to 'main'
    changes:
      - Backend/**/*    # more specifically - only when changes are made inside the 'Backend' folder

