image: maven:3.9-openjdk-17

stages:
  - mavenbuild
  - maventest

maven-build:
  stage: mavenbuild
  tags:
    - brayden_tag
  script:
    - cd Backend
    - mvn package
  only:
    refs:
      - Brayden_CICD
    changes:
      - Backend/**/*

maven-test:
  stage: maventest
  tags:
    - brayden_tag
  script:
    - cd Backend
    - mvn test
  only:
    refs:
      - Brayden_CICD
    changes:
      - Backend/**/*